name: .NET Build and Godot Test

on:
  push:
    branches: [ "automated-pipeline-testing" ]
  pull_request:
    branches: [ "main" ]

env:
  GODOT_BIN: '/root/.local/share/godot/templates/4.2.1.stable.mono ~/.local/share/godot/export_templates/4.2.1.stable.mono'

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build GodotVoipNet.sln

      - name: Test
        run: dotnet test --no-build GodotVoipNet.sln

      # - name: Get GodotPath
      #   run: |
      #     cd /root/.local/share/godot/templates
      #     echo $(ls)
